# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()

a2=np.array([[1,3.3,5],[3,5,6]])
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,3,5],
             [3,5,7]],
            [[3,5,6],
            [4,6,5]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.size,a2.dtype,type(a2)

((2, 3), 2, 6, dtype('float64'), numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape,a3.size,a3.dtype,a3.ndim,type(a3)

((2, 2, 3), 12, dtype('int32'), 3, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  3.3  5.0
1  3.0  5.0  6.0

In [12]:
# Create an array of shape (10, 2) with only ones
one=np.ones(shape=(10,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zero= np.zeros(shape=(7,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
arange=np.arange(0,100,3)
arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand=np.random.randint(10,size=(7,2))
rand

array([[2, 0],
       [7, 4],
       [3, 4],
       [6, 3],
       [5, 6],
       [6, 5],
       [3, 1]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand2=np.random.random((3,5))
rand2

array([[0.3646646 , 0.71787922, 0.6020345 , 0.14902054, 0.20503331],
       [0.39369564, 0.13329504, 0.5333998 , 0.75115968, 0.27576562],
       [0.44571017, 0.37520264, 0.02990228, 0.70985495, 0.96876644]])

In [25]:
# Set the random seed to 42

np.random.seed(seed=42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
rand3=np.random.randint(10,size=(4,6))
rand3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [30]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand5=np.random.randint(1,10,(3,7))
rand5
# Find the unique numbers in the array you just created
np.unique(rand5)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [32]:
rand5

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6],
       [2, 9, 5, 6, 4, 7, 9]])

In [31]:
# Find the 0'th index of the latest array you created
rand5[0,0]

7

In [35]:
# Get the first 2 rows of latest array you created
rand5[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
rand5[:2,:2]

array([[7, 9],
       [5, 7]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random=np.random.randint(0,10,(3,5))
one2=np.ones((3,5))

In [38]:
random

array([[6, 0, 0, 8, 8],
       [3, 8, 2, 6, 5],
       [7, 8, 4, 0, 2]])

In [39]:
one2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Add the two arrays together
random+one2

array([[7., 1., 1., 9., 9.],
       [4., 9., 3., 7., 6.],
       [8., 9., 5., 1., 3.]])

In [42]:
# Create another array of ones of shape (5, 3)
one3=np.ones((5,3))
one3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# Try add the array of ones and the other most recent array together
one3+one2.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [44]:
# Create another array of ones of shape (3, 5)
one4=np.ones((3,5))

In [46]:
# Subtract the new array of ones from the other most recent array
one2-one4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
# Multiply the ones array with the latest array
one3*random.T

array([[6., 3., 7.],
       [0., 8., 8.],
       [0., 2., 4.],
       [8., 6., 0.],
       [8., 5., 2.]])

In [50]:
# Take the latest array to the power of 2 using '**'
random**2

array([[36,  0,  0, 64, 64],
       [ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4]])

In [51]:
# Do the same thing with np.square()
np.square(random)

array([[36,  0,  0, 64, 64],
       [ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4]])

In [52]:
# Find the mean of the latest array using np.mean()
np.mean(random)

4.466666666666667

In [53]:
# Find the maximum of the latest array using np.max()
np.max(random)

8

In [54]:
# Find the minimum of the latest array using np.min()
np.min(random)

0

In [55]:
# Find the standard deviation of the latest array
np.std(random)

3.0081371127142607

In [57]:
# Find the variance of the latest array
np.var(random)

9.04888888888889

In [58]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random,(3,5,1))

array([[[6],
        [0],
        [0],
        [8],
        [8]],

       [[3],
        [8],
        [2],
        [6],
        [5]],

       [[7],
        [8],
        [4],
        [0],
        [2]]])

In [59]:
# Transpose the latest array
random.T

array([[6, 3, 7],
       [0, 8, 8],
       [0, 2, 4],
       [8, 6, 0],
       [8, 5, 2]])

What does the transpose do?

In [61]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand6=np.random.randint(10,size=(3,2))
rand7=np.random.randint(10,size=(3,3))

In [63]:
# Perform a dot product on the two newest arrays you created
np.dot(rand7,rand6)

array([[72, 27],
       [65, 66],
       [50, 26]])

In [64]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ran1=np.random.randint(10,size=(4,3))
ran2=np.random.randint(10,size=(4,3))

In [66]:
# Perform a dot product on the two newest arrays you created
np.dot(ran1,ran2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [67]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(ran1,ran2.T)

array([[28, 42, 49, 49],
       [13,  9,  7, 11],
       [65, 73, 72, 83],
       [18,  6,  0,  8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [70]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran1

array([[0, 7, 0],
       [0, 1, 1],
       [5, 6, 4],
       [0, 0, 2]])

In [71]:
ran2

array([[1, 4, 9],
       [5, 6, 3],
       [6, 7, 0],
       [5, 7, 4]])

In [68]:
# Compare the two arrays with '>'
ran1>ran2

array([[False,  True, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [72]:
# Compare the two arrays with '>='
ran1>=ran2

array([[False,  True, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [73]:
# Find which elements of the first array are greater than 7
ran1>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
# Which parts of each array are equal? (try using '==')
ran1==ran2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [75]:
# Sort one of the arrays you just created in ascending 
np.sort(ran1)

array([[0, 0, 7],
       [0, 1, 1],
       [4, 5, 6],
       [0, 0, 2]])

In [76]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran1)

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [77]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ran1)

1

In [78]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran1)

0

In [80]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ran1,axis=1)

array([1, 1, 1, 2], dtype=int64)

In [81]:
ran1

array([[0, 7, 0],
       [0, 1, 1],
       [5, 6, 4],
       [0, 0, 2]])

In [82]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ran1,axis=0)

array([0, 3, 0], dtype=int64)

In [91]:
# Create an array of normally distributed random numbers
arr1=np.random.randn(3,5)
arr1

array([[-0.16093738, -0.3882644 , -0.88551237, -0.35674503,  0.5561218 ],
       [ 1.04386061,  0.52644816,  1.36388652,  2.53916272, -0.32449096],
       [-0.20586672, -1.44004145,  1.19072726,  1.29939681, -0.86714616]])

In [92]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr2=np.linspace(1,100,10)
arr2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.